# -*- coding: utf-8 -*-
"""CIE-1pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hfhpgnn0MblZ6K4y6f1uk1mXvmBfg2uN
"""

import pandas as pd
a = pd.Series([1,2,3,4,5])
b = pd.Series([2,4,6,8,10])
d=a[a.isin(b)]
e=b[b.isin(a)]
print("Elements in 'a' not in 'b':")
print(d)
print("Elements in 'b' not in 'a':")
print(e)

import pandas as pd
data=pd.read_csv("/content/mtcars.csv")
print(data)

